### PR TITLE
renamed ConvertSaveload::into/from to convert_into/convert_from

### PR DESCRIPTION
**Pull request by expenses**
See #503.

---
This change is [Reviewable](https://reviewable.io/reviews/slide-rs/specs/504)

### CODE REVIEW

**Comment by torkleyy** [comment]
Let's try again.
bors r+

**Comment by expenses** [comment]
Oops, forgot to run the tests will all features

**Comment by torkleyy** [comment]
Okay, no worries, just push more commits until it works :wink:

**Comment by torkleyy** [comment]
Ah sorry, I misunderstood. It's already fixed.
bors r+

**Pull request merged**
