### PR TITLE
Add more constructors

### PR DESCRIPTION
**Pull request by torkleyy**
* Use the number of cpus as pool size
* Allows sharing the thread pool

### CODE REVIEW

**Comment by kvark** [comment]
Why don't you want to simply remove the constructor that accepts a number of threads? I don't see many consumers of this one, and they can work around by creating `ThreadPool` themselves.

**Comment by torkleyy** [comment]
As @nchash wrote

> Maybe add a Planner::new, taking a usize and Planner::new_num_cpus. There are use cases where you don't need an Arc<ThreadPool> and you need to set the number of threads (for example to benchmark performance with and without multithreading).

> And from the user's perspective it isn't obvious that the way you get a Planner with a set number of threads is call Planner::from_pool.

Additionally, doing it that way is non breaking and easier to understand what it does from the function name. 

And there's not really a disadvantage of having one more function.

**Comment by kvark** [comment]
Well, I don't agree with @nchash proposal here. I think `new()` should be dumb simple and good for everyone, so having no parameters is great.

> There are use cases where you don't need an Arc and you need to set the number of threads (for example to benchmark performance with and without multithreading).

The non-multithreaded mod is a bigger task - #72 , we don't need to cater for it since we don't yet know how it is going to work.

> And from the user's perspective it isn't obvious that the way you get a Planner with a set number of threads is call Planner::from_pool.

As I said, a regular user would not care. An advanced user would figure `from_pool` out.

> Additionally, doing it that way is non breaking ...

Don't worry about breaking too much. We are on the verge of 0.8, which is fine to break API a little.

> ... and easier to understand what it does from the function name.

The easiest thing to understand is `new()` without parameters, and that's what I'm arguing for.

> And there's not really a disadvantage of having one more function.

Sure thing, as long as you keep the most used case unencumbered. So, it's fine to have an extra `with_num_threads` constructor, but not fine to have `usize` parameter for `new()`.

**Comment by torkleyy** [comment]
@kvark Good idea, did that

**Comment by kvark** [comment]
Thanks @torkleyy ! Last things - make CI happy and squash the commits please.

**Pull request merged**
