### PR TITLE
[WIP] Tracked Interface

### PR DESCRIPTION
**Pull request by Aceeri**
todo:
- Remove `TrackedStorage`?
- Add `ChangedStorage` (`FlaggedStorage` + comparisons)
- Should the `Tracked::Modified/Inserted/Removed` be `Join` or `BitSetLike`?
- How to deal with `&mut storage` & `storage.modified()` together.

---
This change is [Reviewable](https://reviewable.io/reviews/slide-rs/specs/305)

### CODE REVIEW

**Comment by torkleyy** [comment]
How will this interact with #301 ?

**Comment by torkleyy** [comment]
A chapter about component metadata would be helpful after this is merged.

**Comment by Aceeri** [comment]
> How will this interact with #301 ?

#301 will be closed after this is finished.

**Comment by torkleyy** [comment]
Thanks for the PR, I want to review in a few hours (if I don't forget it). Just a note, there's a little conflict with the changelog.

**Comment by torkleyy** [comment]
This is great, thank you so much! I have to take a closer look at the `track` module, the rest looks great.

---

Reviewed 1 of 5 files at r1, 5 of 9 files at r3, 2 of 5 files at r4.
Review status: 8 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[examples/track.rs, line 26 at r4](https://reviewable.io:443/reviews/slide-rs/specs/305#-L-g3UZo4RwFzC9yCS5J:-L-g3UZo4RwFzC9yCS5K:bwtumeg) ([raw file](https://github.com/slide-rs/specs/blob/50042543d485ebc513b2fbadb4c0c89d36e3e20d/examples/track.rs#L26)):*
> ```Rust
>     );
>     fn run(&mut self, (entities, tracked): Self::SystemData) {
>         if let None = self.modified_id {
> ```

This should use match and return the reader id.

---

*[src/lib.rs, line 219 at r4](https://reviewable.io:443/reviews/slide-rs/specs/305#-L-g4-yksKskfsKjGdQo:-L-g4-yl4Bt1XtBkozK7:b-qfo1fd) ([raw file](https://github.com/slide-rs/specs/blob/50042543d485ebc513b2fbadb4c0c89d36e3e20d/src/lib.rs#L219)):*
> ```Rust
> pub use shred::AsyncDispatcher;
> 
> pub use storage::{BTreeStorage, Capacity, DefaultCapacity, DenseVecStorage, DistinctStorage,
> ```

Yes, we do need to organize this.

---

*[src/storage/flagged.rs, line 76 at r4](https://reviewable.io:443/reviews/slide-rs/specs/305#-L-g4II35P-eE1soytFo:-L-g4II35P-eE1soytFp:b-t77d2x) ([raw file](https://github.com/slide-rs/specs/blob/50042543d485ebc513b2fbadb4c0c89d36e3e20d/src/storage/flagged.rs#L76)):*
> ```Rust
> ///#        let condition = true;
> ///         for (entity, _) in (&*entities, &comps.check()).join() {
> ///             if condition { // check whether this component should be modified.
> ```

Should this use the restricted storage?

---

*[src/storage/flagged.rs, line 115 at r4](https://reviewable.io:443/reviews/slide-rs/specs/305#-L-g4O23PdsALGSGPa10:-L-g4O23PdsALGSGPa11:bq4agx4) ([raw file](https://github.com/slide-rs/specs/blob/50042543d485ebc513b2fbadb4c0c89d36e3e20d/src/storage/flagged.rs#L115)):*
> ```Rust
>     fn default() -> Self {
>         FlaggedStorage {
>             modified: EventChannel::with_capacity(Cap::Modify),
> ```

I don't agree with this strategy, but don't have a constructive suggestion at the moment.

---

*[src/storage/track.rs, line 192 at r4](https://reviewable.io:443/reviews/slide-rs/specs/305#-L-g4sVrOeKdQDo4UyV-:-L-g4sVrOeKdQDo4UyV0:b-ubdx0d) ([raw file](https://github.com/slide-rs/specs/blob/50042543d485ebc513b2fbadb4c0c89d36e3e20d/src/storage/track.rs#L192)):*
> ```Rust
> 
> /// Clears and populates a structure with an event channel's contents.
> pub trait Populate<T> {
> ```

Do we really need to export this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/slide-rs/specs/305#-:-L-g4w62DYFHsF51fi8x:bqtbcch)*

**Pull request closed without merging**
