### PR TITLE
Add tests for tracking component insertions / removals

### PR DESCRIPTION
**Pull request by torkleyy**
@Rhuagh how was our strategy for keeping track of all the existing components?

Related: #361

---
This change is [Reviewable](https://reviewable.io/reviews/slide-rs/specs/463)

### CODE REVIEW

**Comment by GraemeWilde** [comment]
I saw your comment in #361, what part are you trying to figure out?

**Comment by torkleyy** [comment]
I know how you could do it; I just thought there was a concise way to do
this. I'm considering to add a better API and / or change the existing one.

**Comment by torkleyy** [comment]
Rhuagh suggested that we could merge all events into a single channel so we get the order of the events. I generally like the idea, I'm just worried it'll leave us with a worse access pattern.

**Comment by torkleyy** [comment]
Another option would be to leave the API as-is and create a wrapper that does all the black magic that makes the current API difficult. Rhuagh's solution would be a lot cleaner though..

**Comment by torkleyy** [comment]
Closing due to inactivity.

**Pull request closed without merging**
