### PR TITLE
Use rayon instead of threadpool

### PR DESCRIPTION
**Pull request by torkleyy**
This PR does not implement scoped parallel execution, but can be used as a basis for that.

Fixes https://github.com/slide-rs/specs/issues/124

### CODE REVIEW

**Comment by torkleyy** [comment]
@kvark seems rayon is propagating the panics differently. Any clue how to solve this?

**Comment by WaDelma** [comment]
You can see fix to the panic problem in my [pr](https://github.com/WaDelma/specs/blob/e5263113da6c7d3a58b0c6d46c1b8406159945d6/src/planner.rs#L126)

**Comment by torkleyy** [comment]
@kvark would it be okay to just have rayon as a thread pool for now?

**Comment by kvark** [comment]
@torkleyy I think so. Eventually, we'd like `rayon` to at least often be used with `specs`, if not by `specs`.

**Pull request merged**
