### PR TITLE
Implement Join on BitSetLike trait object

### LINKED ISSUE #598: Join impl for BitSetLike trait object
## Description
Implement `Join` on `&dyn BitSetLike`.

## Motivation
Enables support for conditionally choosing between different `BitSetLike` types to use in a `Join`.

For example:
```rust
let first = BitSet::new();
let second = !&first;
let cond = true;
let bitset: &dyn BitSetLike = if cond {
    &first
} else {
    &second
};
bitset.join();
```

## Drawbacks

* Relies on dynamic trait objects & dynamic dispatch which _might_ not be as fast as static dispatch

## Unresolved questions

---

I'd gladly like to work on this ticket once it's approved.

### PR DESCRIPTION
**Pull request by algonomicon1**
Fixes #598 

## Checklist

* [x] I've added tests for all code changes and additions (where applicable)
* [x] I've added a demonstration of the new feature to one or more examples
* [x] I've updated the book to reflect my changes
* [x] Usage of new public items is shown in the API docs

## API changes

----
Merging this PR requires slide-rs/hibitset#45 to be merged in some release. Then this PR wouldn't require a `Cargo.toml` change.

I didn't actually do the checklist. Are any of the items required for this change?

### CODE REVIEW

**Comment by torkleyy** [comment]
> just want to release a new version of hibitset

Ah, so that's actually something I should do at some point :sweat_smile:

**Comment by torkleyy** [comment]
I've published `hibitset` 0.6.0.

**Comment by algonomicon1** [comment]
Thanks @torkleyy, I've updated `Cargo.toml`.

FYI - seems like versions in `Cargo.toml` and `README.md` on [slide-rs/hibitset repo](https://github.com/slide-rs/hibitset) are lagging behind [crates.io/hibitset](https://crates.io/crates/hibitset) ("0.6.0" vs "0.5.4" and "0.1" respectively).

**Comment by torkleyy** [comment]
> FYI - seems like versions in Cargo.toml and README.md on slide-rs/hibitset repo are lagging behind crates.io/hibitset ("0.6.0" vs "0.5.4" and "0.1" respectively).

Oops, thank you, I totally forgot pushing my commit :smile: 

Let's get this merged! :shipit: 
bors r+

**Pull request merged**
