### PR TITLE
DeferredStorage

### PR DESCRIPTION
**Pull request by Aceeri**
I can revert the rename if we want, but I'd like the other changes since they make the storage a lot nicer to use.

- Renames RestrictedStorage to DeferredStorage.
- Removes Entry/EntityIndex in favor of just storing the index in the returned storage.
- Also removes a clone from the mutably RestrictedStorage.

Should we have `Deref`/`DerefMut` access on the PairedStorage? It could be handy for cleaner code, but it would make the deferred access a bit more implicit which could lead to some more annoying maintenance bugs for people. (Accidentally move a mutable modification outside of a condition which then marks all components are modified).

---
This change is [Reviewable](https://reviewable.io/reviews/slide-rs/specs/324)

### CODE REVIEW

**Comment by torkleyy** [comment]
> Should we have Deref/DerefMut access on the PairedStorage?

No, I think it's better to remove it and make the access explicit.

---

Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/slide-rs/specs/324#-:-L1LhsYQouA6jV-cyIKq:blnuhbb)*

**Comment by Aceeri** [comment]
@torkleyy IIRC this is ready (just need to rebase)

**Comment by torkleyy** [comment]
Looks good to me. Some more reviews would be helpful, cc @Rhuagh @Xaeroxe

---

Reviewed 1 of 8 files at r1, 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/storage/restrict.rs, line 32 at r2](https://reviewable.io:443/reviews/slide-rs/specs/324#-L4uq-sjtjKt3I6W0GvL:-L4uq-sjtjKt3I6W0GvM:birjy4m) ([raw file](https://github.com/slide-rs/specs/blob/9331c649cb797b42e12c121dc605c999666f23f6/src/storage/restrict.rs#L32)):*
> ```Rust
> 
> /// Similar to a `MaskedStorage` and a `Storage` combined, but restricts usage
> /// to only getting and modifying the components. That means nothing that would
> ```

Err I think you accidentally removed some lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/slide-rs/specs/324#-:-L4uqLuH1Pz5eOZ8qAxk:bt48144)*

**Comment by Rhuagh** [comment]
Reviewed 2 of 8 files at r1, 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/slide-rs/specs/324)*

**Comment by Rhuagh** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/slide-rs/specs/324#-:-L4vNnlVuMAVx8qmS7J-:bnfp4nl)*

**Comment by Aceeri** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/storage/restrict.rs, line 32 at r2](https://reviewable.io:443/reviews/slide-rs/specs/324#-L4uq-sjtjKt3I6W0GvL:-L5kxuIWIO4mpcK5OBnx:b-896fix) ([raw file](https://github.com/slide-rs/specs/blob/9331c649cb797b42e12c121dc605c999666f23f6/src/storage/restrict.rs#L32)):*
<details><summary><i>Previously, torkleyy (Thomas Schaller) wrote…</i></summary><blockquote>

Err I think you accidentally removed some lines
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/slide-rs/specs/324)*

**Comment by Rhuagh** [comment]
Reviewed 7 of 8 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/slide-rs/specs/324)*

**Pull request merged**
