### PR TITLE
Update to rayon 1.0

### PR DESCRIPTION
**Pull request by cuviper**
This will need new versions of hibitset and shred too, so they'll all agree on rayon 1.0.
- [x] slide-rs/hibitset#30
- [x] slide-rs/shred#76

cc amethyst/amethyst#579

---
This change is [Reviewable](https://reviewable.io/reviews/slide-rs/specs/352)

### CODE REVIEW

**Comment by torkleyy** [comment]
Sorry for the delay! I've just released hibitset 0.5, shred will follow as soon as I merged the open PR.

**Comment by Rhuagh** [comment]
Is shred released?

**Comment by torkleyy** [comment]
Yes, a few seconds ago.

**Comment by cuviper** [comment]
@torkleyy shred-0.6.1 appears to be a breaking change here:

```
error[E0050]: method `fetch` has 1 parameter but the declaration in trait `shred::SystemData::fetch` has 2
   --> src/storage/data.rs:117:19
    |
117 |     fn fetch(res: &'a Resources) -> Self {
    |                   ^^^^^^^^^^^^^ expected 2 parameters, found 1
    |
    = note: `fetch` from trait: `fn(&'a shred::Resources, usize) -> Self`

error[E0050]: method `reads` has 0 parameters but the declaration in trait `shred::SystemData::reads` has 1
   --> src/storage/data.rs:121:5
    |
121 | /     fn reads() -> Vec<ResourceId> {
122 | |         vec![
123 | |             ResourceId::new::<EntitiesRes>(),
124 | |             ResourceId::new::<MaskedStorage<T>>(),
125 | |         ]
126 | |     }
    | |_____^ expected 1 parameter, found 0
    |
    = note: `reads` from trait: `fn(usize) -> std::vec::Vec<shred::ResourceId>`

error[E0050]: method `writes` has 0 parameters but the declaration in trait `shred::SystemData::writes` has 1
   --> src/storage/data.rs:128:5
    |
128 | /     fn writes() -> Vec<ResourceId> {
129 | |         vec![]
130 | |     }
    | |_____^ expected 1 parameter, found 0
    |
    = note: `writes` from trait: `fn(usize) -> std::vec::Vec<shred::ResourceId>`
```

**Comment by torkleyy** [comment]
How is that possible? I must have done something wrong when using git..

**Comment by torkleyy** [comment]
Maybe this is just using the wrong `shred-derive` version?

**Comment by torkleyy** [comment]
This file looks just right: https://github.com/slide-rs/shred/blob/v0.6/src/system.rs#L80

**Comment by torkleyy** [comment]
Nothing changed since 0.6

**Comment by cuviper** [comment]
FWIW shred-0.6.0 used shred-derive-0.4.0, but shred-0.6.1 uses shred-derive-0.3.0.

**Comment by torkleyy** [comment]
Oh

**Comment by torkleyy** [comment]
Now I know what's wrong

**Comment by torkleyy** [comment]
Sorry for the mess, should work now.

**Comment by cuviper** [comment]
OK, I think we're all set here!

**Pull request merged**
