### PR TITLE
Make it possible to disable parallel feature

### PR DESCRIPTION
**Pull request by omni-viral**
This makes it possible to user specs in wasm environment

---
This change is [Reviewable](https://reviewable.io/reviews/slide-rs/specs/495)

### CODE REVIEW

**Comment by omni-viral** [comment]
> threading support in wasm

Does wasm support threading at all?

**Comment by torkleyy** [comment]
Well, not "enough" yet. There are some experimental things supported only
in Chrome I believe, but for the most part it's currently unsupported.

On Oct 18, 2018 16:07, "Zakarum" <notifications@github.com> wrote:

threading support in wasm

Does wasm support threading at all?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/slide-rs/specs/pull/495#issuecomment-431022621>, or mute
the thread

**Comment by Xaeroxe** [comment]
Oh just re-read @torkleyy 's comment my bad

bors r-

**Comment by omni-viral** [comment]
Without making code super-inconsistent I managed to reduce amount of `#[cfg(feature = "parallel")]` slightly.

**Comment by torkleyy** [comment]
Wow.

*should we care about

**Comment by omni-viral** [comment]
Emmm. I checked it with wasm :)

**Comment by drager** [comment]
I can confirm this works. I tried out @omni-viral's branch with the same code that wasn't working before this PR and now it works.

**Pull request merged**
